### ISSUE TITLE
Ошибка: выгрузка больших файлов поделенных на части

### ISSUE THREAD

**Issue by Serokuz22** [bigperson/exchange1c#3]
src/Services/FileLoaderService.php
строка55  $f = fopen($filePath, 'w+');
нужно заменить на $f = fopen($filePath, 'a+');
чтобы он дописывал в конец а не перезаписывал

**Comment by bigperson** [comment]
@Serokuz22 на больших выгрузках не тестировали. Буду признателен за пулл реквест
